### PR TITLE
Feature/ui

### PR DESCRIPTION
**Pull request by callicles**
Here is a first draft at the UI.

First landing page:
When you click on the user name it gets you to the user profile on github.
The field in the center should get you to the repository reference you type in.
Contribute on Github is a link to the project.
`Build #15` is generated when using the test comment in an environment with the `CIRCLE_BUILD_NUM` so that we can track deployed versions.
screen shot 2015-08-13 at 8 12 11 pm

Repository page.
This is the page where you get the gist of a repository. Normally, the scores should converge and underline a trend. That's why we want to use parallel coordinates. You can yourself rate a repository from here by clicking on the `Give Feedback` button. 
screen shot 2015-08-14 at 2 18 32 pm

When a user clicks on `Give feedback` it shows this screen.
Here he is supposed to  score the repository by clicking on the stars to rate each criteria and then leave a comment with it.
screen shot 2015-08-14 at 2 53 03 pm

When a user uses an unlawful address. The field is there to allow him to go to a repository page.
screen shot 2015-08-13 at 6 35 32 pm

As for the parallel coordinates, [it is not possible](https://github.com/syntagmatic/parallel-coordinates/issues/118) at the moment to change the transparency of the lines according to a value in the data (for us time). I will try to get on to that when we will have the system working.

@sheymann @pocman @jacobtardieu please comment.

### CODE REVIEW

**Comment by sheymann** [comment]
Hey, why parallel coordinates? Why not radar charts or simply bar charts? FYI parallel coordinates are usually hard to read and make sense on analytics, interactive tasks only. Their puprose is to help find multiple trends if trends exists.

What do the icons below each feedback mean? I don't know by looking at the first page only.

More generally, can you re-organize your frames to stick to user scenarii? Start/end, purpose of the frame, actions expected by the user.

**Comment by pocman** [comment]
That's sick.

@sheymann : Hey, why parallel coordinates? Why not radar charts or simply bar charts? FYI parallel coordinates are usually hard to read and make sense on analytics, interactive tasks only. Their purpose is to help find multiple trends if trends exists.
=> This is exactly why we want to use them. At first, we'll have few data and averages won't make sense. Radar charts is just a circular averaged parallel coordinates.
When we'll have more data we will make some clusters and then averaged each of them by sum of karmas.

@callicles : Can we set transparency for every line so that overlapping ones become darker ?

**Comment by callicles** [comment]
@pocman We can set overall transparency, we even can set the view to be "brushable" which is basically interactive filtering on coordinates.

@sheymann The icons on each feedback corresponds to the scores given per criteria by the user. I agree this is not really clear as a snapshot, the html version is actually interactive, you get a caption with the description when you hover the icon. It says (in order) `Documentation` `Maturity` `Design` `Support`.

**Comment by callicles** [comment]
screen shot 2015-08-14 at 2 18 32 pm

**Comment by sheymann** [comment]
Thanks for the update, now this is my point of view on the repo page: it gives too much emphasis on the analytics and not enough on feedback. 

We expect that good feedback is detailed and contains a few paragraphs. Feedback should be at the center of attention because it is direct valuable information. Then score is the second valuable information, but each score makes sense only if related to a feedback. And finally we may be interested by the global trend because it is not an information directly interpretable. A solution would be to split feedback and analytics into two different pages, with feedback directly accessible to focus people on the content instead of the numbers. 

Reason: feedback should be useful to repo's authors first, then global score (a derived information) may be useful to third-party developers. Otherwise the risk is that repo's authors reject and blame gitrank, reducing the incentive to give feedback. The design of this page will directly impact the way gitrank is perceived.

Also, `Give Feedback` is too similar to general "feedback" buttons on websites. Here it looks like I will give feedback to gitrank's website.

**Comment by callicles** [comment]
Good points, let me think about it. We will try to connect the dots between back and front with this but it does need changes.

**Comment by callicles** [comment]
@sheymann 
What I think is the most value proposition is to enable easy comparison between repositories for developers/users of the projects. This is what's gonna be used by most of people because there are more people using open source than people producing open source. In that sense feedback is there to give depth to a given user score. 

The fact that it can be useful for contributors is kind of a bonus and a way to get people to put badges on their repositories to engage people. 

That being said, I agree with the fact that it can cause author's to blame gitrank and reject it.

As such I would propose a  different  "view" of this page for the contributors of the project. Since we know who contributed, we can change how the page renders for contributors in order to focus on the feedback.

* Anonymous users and non contributors would see the page as is. 
* The contributors would see a different page with a focus on feedback.

Totally agree with the `Give Feedback` Button, will find out how to change that.

**Comment by pocman** [comment]
I agree for the two views. 

For the give feedback, we have multiple option. 

In think it should be at the center or the right of the page (not the left which is where most of website feedback plug-in are). 

Rank this project
Give your gitrank

**Comment by callicles** [comment]
A little change: integration of the access field in the navbar

screen shot 2015-08-30 at 7 27 34 pm

Change of the give feedback button place and text + updated navbar

screen shot 2015-08-30 at 7 27 54 pm
Same but with logged in user
screen shot 2015-08-30 at 7 28 24 pm

Feedback page.
From @sheymann remarks on feedbacks and the influence of having seen scores before giving some feedback, I followed the suggestion and put the feedback form on another page. That way this page could be directly linked from a `Give Feedback` github page and prevent user from seeing the scores before their give their feedback.
screen shot 2015-08-30 at 7 28 28 pm

Screen to be shown if the repository exists but has no feedback yet.
screen shot 2015-08-30 at 7 29 11 pm

The second view for the repository owner will be designed later when the already designed features are working

**Pull request merged**
